[project]
name = "cluster-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "logging>=0.4.9.6",
    "mcp>=1.25.0",
    "ollama>=0.6.1",
    "pydantic>=2.12.5",
]
